name = "StreamCallbacks"
uuid = "c1b9e933-98a0-46fc-8ea7-3b58b195fb0a"
authors = ["J S <49557684+svilupp@users.noreply.github.com> and contributors"]
version = "0.2.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
Aqua = "0.8"
HTTP = "1.10"
JSON3 = "1.14"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
